### ISSUE TITLE
applyfairytype.bat not working

### ISSUE THREAD

**Issue by PlaidManiacZ** [BluRosie/b2w2-fairy#1]
I'm having a couple of issues running applyfairytype.bat. Each time I try and run it, my computer gives me errors for not having specific programs. It mentions Libstdc++-6.dll , VCRUNTIME140.dll , and Msvcp140.dll not being found. I am unsure if this is because they are not included in the full download provided or if they are and are simply in a strange part that it cannot find.

<img width="317" alt="Capture" src="https://user-images.githubusercontent.com/91800146/188294627-120313bc-635b-400d-9dd6-b4f6542ef7ac.PNG">
<img width="314" alt="Capture01" src="https://user-images.githubusercontent.com/91800146/188294628-59bc4d17-64a5-4391-92f1-39e256268fa2.PNG">
<img width="307" alt="Capture02" src="https://user-images.githubusercontent.com/91800146/188294630-ac3c4a87-1005-4365-8d46-f99bfdb64421.PNG">

I understand if it is just me being dumb because it would be tbh, don't before afraid to make fun of me.

**Comment by BluRosie** [comment]
howdy!!  replaced the ndstool with a different one that should work better.  let me know if that doesn't work!

**Comment by PlaidManiacZ** [comment]
Thank you so much! That seemed to work. Oh, and it was no problem for me since I used MeroMero's guide for the graphics parts, but file a082_51.RGCN opens to an error page. Again, no problem for me, just thought you should know

**Comment by BluRosie** [comment]
fixed that link too!  thank you so much 😁
